#通用配置
server:
  port: 9777
  servlet:
    context-path: /iron
spring:
  profiles:
   active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

iron:
  baseUrl: http://localhost:${server.port}${server.servlet.context-path}