# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iron?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
  session:
    store-type: none

# 配置日志打印
logging:
  level:
    run.aquan.iron.*: debug

